package com.ashwetaw.springbootgenericcrud.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;


/**
 * @author koheincs
 * @created at 08/04/2024
 **/

@Data
@DynamoDBTable(tableName = "country")
public class Country {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    private String name;
    private String description;
    private String code;

}
