package com.ashwetaw.springbootgenericcrud.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

/**
 * @author koheincs
 * @created at 07/04/2024
 **/
@Getter
@Setter
@Data
@DynamoDBTable(tableName = "department")
public class Department {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    private String name;
    private String description;
    private String email;
    private String phone;


    public Department() {}

}
